from convlab.laug.Word_Perturbation.Word_Perturbation import Word_Perturbation
from convlab.laug.Text_Paraphrasing.Text_Paraphrasing import Text_Paraphrasing
from convlab.laug.Speech_Recognition.Speech_Recognition import Speech_Recognition
from convlab.laug.Speech_Disfluency.Speech_Disfluency import Speech_Disfluency